# Generated by Django 5.1.5 on 2025-01-31 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'field',
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('name', models.TextField(unique=True)),
                ('mass_kg', models.FloatField()),
                ('pref_temperature', models.FloatField(blank=True, null=True)),
                ('pref_humidity', models.FloatField(blank=True, null=True)),
                ('pref_soil_moisture', models.FloatField(blank=True, null=True)),
                ('pref_nutrient_level', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seed',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Landwirt', 'Landwirt'), ('Mechaniker', 'Mechaniker'), ('Manager', 'Manager')], default='Landwirt', max_length=255)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmershub.field')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='FieldMeasurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('row', models.BigIntegerField()),
                ('column', models.BigIntegerField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('soil_moisture', models.FloatField(blank=True, null=True)),
                ('nutrients_level', models.FloatField(blank=True, null=True)),
                ('health_score', models.FloatField(blank=True, null=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmershub.field')),
            ],
            options={
                'db_table': 'field_measurement',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('In Betrieb', 'In Betrieb'), ('Wartung erforderlich', 'Wartung erforderlich'), ('Defekt', 'Defekt')], default='In Betrieb', max_length=255)),
                ('category', models.CharField(choices=[('Traktor', 'Traktor'), ('Mähdrescher', 'Mähdrescher'), ('Anhänger', 'Anhänger'), ('Zubehör', 'Zubehör'), ('Saatmaschine', 'Saatmaschine')], default='Traktor', max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True)),
                ('operating_hours', models.FloatField(default=0.0)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_employees', models.ManyToManyField(blank=True, to='farmershub.employee')),
                ('assigned_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmershub.field')),
            ],
            options={
                'db_table': 'machine',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_machines',
            field=models.ManyToManyField(blank=True, to='farmershub.machine'),
        ),
        migrations.CreateModel(
            name='MachineMaintenance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maintenance_date', models.DateTimeField()),
                ('next_maintenance', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmershub.machine')),
            ],
            options={
                'db_table': 'machine_maintenance',
            },
        ),
        migrations.CreateModel(
            name='MachineMeasurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('fuel_level', models.FloatField(blank=True, null=True)),
                ('engine_temperature', models.FloatField(blank=True, null=True)),
                ('oil_level', models.FloatField(blank=True, null=True)),
                ('rpm', models.FloatField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmershub.machine')),
            ],
            options={
                'db_table': 'machine_measurement',
            },
        ),
        migrations.CreateModel(
            name='MachineUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmershub.employee')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmershub.field')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmershub.machine')),
            ],
            options={
                'db_table': 'machine_usage',
            },
        ),
        migrations.AddField(
            model_name='field',
            name='saat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='farmershub.seed'),
        ),
    ]
