# Generated by Django 5.1.4 on 2025-01-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmershub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fieldmeasurement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seed',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weather',
            options={},
        ),
    ]
