# Generated by Django 5.1.4 on 2025-01-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmershub', '0002_alter_field_options_alter_fieldmeasurement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmeasurement',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldmeasurement',
            name='nutrients_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldmeasurement',
            name='soil_moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldmeasurement',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
