# Generated by Django 5.1.4 on 2025-01-21 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmershub', '0003_field_saat_fieldmeasurement_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='saat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='farmershub.seed'),
        ),
        migrations.AddField(
            model_name='fieldmeasurement',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='farmershub.field'),
        ),
    ]
