# Generated by Django 5.1.4 on 2025-01-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmershub', '0004_delete_weather_field_saat_fieldmeasurement_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
