# Generated by Django 5.1.4 on 2025-01-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmershub', '0005_delete_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='size',
        ),
        migrations.AddField(
            model_name='field',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
