# Generated by Django 5.1.4 on 2025-01-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmershub', '0006_remove_field_size_field_height_field_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='pref_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seed',
            name='pref_nutrient_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seed',
            name='pref_soil_moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seed',
            name='pref_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
