# Generated by Django 5.1.5 on 2025-01-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmershub', '0007_seed_pref_humidity_seed_pref_nutrient_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
