# Generated by Django 5.1.5 on 2025-01-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmershub', '0008_alter_field_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
