# Generated by Django 5.1.5 on 2025-01-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmershub', '0009_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmeasurement',
            name='health_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
