# Generated by Django 5.1.5 on 2025-01-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmershub', '0010_fieldmeasurement_health_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('In Betrieb', 'In Betrieb'), ('Wartung erforderlich', 'Wartung erforderlich'), ('Defekt', 'Defekt')], default='In Betrieb', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'machine',
            },
        ),
    ]
