# Generated by Django 5.1.5 on 2025-01-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmershub', '0011_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='category',
            field=models.CharField(choices=[('Traktor', 'Traktor'), ('Mähdrescher', 'Mähdrescher'), ('Anhänger', 'Anhänger'), ('Zubehör', 'Zubehör'), ('Saatmaschine', 'Saatmaschine')], default='Traktor', max_length=50),
        ),
    ]
