# Generated by Django 5.1.5 on 2025-01-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmershub', '0012_machine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
