# Generated by Django 5.1.5 on 2025-01-31 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmershub', '0013_machine_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='assigned_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmershub.field'),
        ),
        migrations.AddField(
            model_name='machine',
            name='operating_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='year_of_manufacture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldmeasurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fieldmeasurement',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmershub.field'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Landwirt', 'Landwirt'), ('Mechaniker', 'Mechaniker'), ('Manager', 'Manager')], default='Landwirt', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmershub.machine')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmershub.employee'),
        ),
        migrations.CreateModel(
            name='MachineMaintenance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maintenance_date', models.DateTimeField()),
                ('next_maintenance', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmershub.machine')),
            ],
            options={
                'db_table': 'machine_maintenance',
            },
        ),
        migrations.CreateModel(
            name='MachineMeasurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('fuel_level', models.FloatField(blank=True, null=True)),
                ('engine_temperature', models.FloatField(blank=True, null=True)),
                ('oil_level', models.FloatField(blank=True, null=True)),
                ('rpm', models.FloatField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmershub.machine')),
            ],
            options={
                'db_table': 'machine_measurement',
            },
        ),
        migrations.CreateModel(
            name='MachineUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmershub.employee')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmershub.field')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmershub.machine')),
            ],
            options={
                'db_table': 'machine_usage',
            },
        ),
    ]
